runtime: python39

# Storing values in environment variables. This use is optional but convenient
env_variables:
  APP_NAME: 'dldi-lab-e99e51' # the google app engine projet id
  DOMAIN_NAME: 'dldi-lab-e99e51.uc.r.appspot.com'
  IMGIX_ROOT: '/'
  DEFAULT_LANGUAGE: 'en'
  BRAND: 'dldi'

handlers:
  # This configures Google App Engine to serve the files in the app's static directory.
- url: /static
  static_dir: static
  expiration: 7d

  # Moves ico/txt/png from the root folder to the server root. Used for icons and robots.txt
- url: /(.*\.(ico|txt|png))
  static_files: root/\1
  upload: root/.*\.(ico|txt|png)

  # This handler routes all requests not addressed above to the main app. 
- url: /.*
  script: auto
  secure: always
